- name: Import Common role
  ansible.builtin.import_role:
    name: common

- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Remove old html content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Download frontend Content & extract it
  ansible.builtin.unarchive:
    src: "https://github.com/roboshop-devops-project/frontend/archive/main.zip"
    dest: /tmp
    remote_src: yes

- name: Copy Frontend Content
  ansible.builtin.copy:
    src: /tmp/frontend-main/static/
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Copy Roboshop Config File
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Restart Nginx Server
  ansible.builtin.systemd:
    state: restarted
    name: nginx