- name: Setup Yum Repos
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash

- name: Install RabbitMQ
  ansible.builtin.yum:
    name:
      - https://github.com/rabbitmq/erlang-rpm/releases/download/v25.1/erlang-25.1-1.el8.x86_64.rpm
      - rabbitmq-server
    state: installed

- name: Start RabbitMQ Service
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: Add a roboshop Application user
  communtiy.rabbitmq.rabbitmq_user:
    user: roboshop
    password: "{{RABBITMQ_PASSWORD}}"
    tags: administrator
    permissions:
      - vhosts: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present