groups:
  - name: Alerts
    rules:
      - alerts: InstanceDown
        expr: up==0
        for: 1m
        labels:
          severity: critical
        annotations: {% raw %}
          summary: "Instance Down - [{{ $labels.instance }}]"
